#! /usr/bin/env python2.7
# Native Messaging script to launch video player
import os
import struct
import sys
import json
import subprocess
try:
    #taken from the native messaging host example 
    #https://chromium.googlesource.com/chromium/src/+/master/chrome/common/extensions/docs/examples/api/nativeMessaging/host/native-messaging-example-host

    #put windows stdin/stdout in binary mode
    if sys.platform == "win32":
        import os, msvcrt 
        msvcrt.setmode(sys.stdin.fileno(), os.O_BINARY)
        msvcrt.setmode(sys.stdout.fileno(), os.O_BINARY)

    binaryLength = sys.stdin.read(4)
    if len(binaryLength) == 0:
        sys.exit(0)

    msgLength = struct.unpack('i',binaryLength)[0]
    text = str(sys.stdin.read(msgLength).decode('utf-8'))
    dic =  json.loads(text)
    arguements = dic["player"].split(",")
    arguements.append(dic["link"])
    subprocess.check_call(arguements)
    sys.exit(0)

except Exception as e:
    text_file = open("Error.log", "w")
    text_file.write('\nError on line {}'.format(sys.exc_info()[-1].tb_lineno))
    text_file.write( e.__doc__)
    text_file.write(e.message)
    text_file.close()
