#! /usr/bin/env python
# Native Messaging script to launch video player
import struct
import sys
import json
import subprocess

try:
    #taken from the native messaging host example 
    #https://chromium.googlesource.com/chromium/src/+/master/chrome/common/extensions/docs/examples/api/nativeMessaging/host/native-messaging-example-host
    if sys.platform == "win32":
        import os, msvcrt 
        msvcrt.setmode(sys.stdin.fileno(), os.O_BINARY)
        msvcrt.setmode(sys.stdout.fileno(), os.O_BINARY)
    msg_lengthBI = sys.stdin.read(4)
    if len(msg_lengthBI) == 0:
        sys.exit(0)
    msg_length = struct.unpack('i',msg_lengthBI)[0]
    text = str(sys.stdin.read(msg_length).decode('utf-8'))
    dic =  json.loads(text) 
    player =dic["player"]
    link = dic["link"]
    exit_code = subprocess.call([player, link])

except Exception as e:
    text_file = open("Error.log", "w")
    text_file.write( e.__doc__)
    text_file.write(e.message)
    text_file.close()
